# Generating Numbers using NumPy

In [1]:
import numpy as np

# np.empty()

In [2]:
empty_array = np.empty(shape=(3,3), dtype=np.float)
print(empty_array)

[[0.000e+000 0.000e+000 0.000e+000]
 [0.000e+000 0.000e+000 6.403e-321]
 [0.000e+000 0.000e+000 0.000e+000]]


# np.zeros()

Matrix of 0's

In [3]:
zeros_array = np.zeros(shape=(3,3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# np.ones()

Matrix of 1's

In [4]:
ones_array = np.ones(shape=(3,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# np.eyes()

Identity Matrix

In [5]:
eyes_array = np.eye(3)
print(eyes_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# np.full()

Matrix filled with Specified Values

In [6]:
full_array = np.full(shape=(3,3), fill_value=7)
print(full_array)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


Also Accept Strings

In [7]:
full_array = np.full(shape=(3,3), fill_value='Kirankumar')
print(full_array)

[['Kirankumar' 'Kirankumar' 'Kirankumar']
 ['Kirankumar' 'Kirankumar' 'Kirankumar']
 ['Kirankumar' 'Kirankumar' 'Kirankumar']]


# Like Functions

In [8]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print(f'Zeros Like Array : \n{np.zeros_like(matrix)}\n')
print(f'Ones Like Array : \n{np.ones_like(matrix)}\n')
print(f'Full Like Array : \n{np.full_like(matrix, fill_value=7)}')

Zeros Like Array : 
[[0 0 0]
 [0 0 0]
 [0 0 0]]

Ones Like Array : 
[[1 1 1]
 [1 1 1]
 [1 1 1]]

Full Like Array : 
[[7 7 7]
 [7 7 7]
 [7 7 7]]


# np.arange()

Output an Array

Similar to Range, Outputs an Object. 

stop / steps 

In [10]:
a = np.arange(start=0, stop=11, step=2)
print(a)

[ 0  2  4  6  8 10]


# Random Generators

Generate Random Variables in NumPy : [NumPy Random Generators](https://numpy.org/doc/stable/reference/random/generator.html) 

In [11]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg  # Bit Generator

In [12]:
array = gen(pcg())
print(array.normal(size=5))

[1.81381358 0.26393219 0.31287552 0.4340815  2.24964387]


In [13]:
print(array.normal(size=(3,3)))

[[ 1.22556992 -0.20907943 -1.23794152]
 [-0.4238896  -0.81597961 -0.49955426]
 [-0.02036614  0.28251445 -2.38721325]]


# Normal Distribution

In [14]:
array = gen(pcg(seed=42))
print(array.normal(size=(5,5)))

[[ 0.30471708 -1.03998411  0.7504512   0.94056472 -1.95103519]
 [-1.30217951  0.1278404  -0.31624259 -0.01680116 -0.85304393]
 [ 0.87939797  0.77779194  0.0660307   1.12724121  0.46750934]
 [-0.85929246  0.36875078 -0.9588826   0.8784503  -0.04992591]
 [-0.18486236 -0.68092954  1.22254134 -0.15452948 -0.42832782]]


# Generate Whole Numbers (integers)

In [15]:
array = gen(pcg(seed=42))
print(array.integers(low=10, high=100,size=(5,5)))

[[18 79 68 49 48]
 [87 17 72 28 18]
 [57 97 76 78 74]
 [80 56 21 85 50]
 [55 43 26 93 80]]


# Probabilities : Numbers between 0 and 1

In [16]:
array = gen(pcg(seed=42))
print(array.random(size=(5,5)))

[[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
 [0.97562235 0.7611397  0.78606431 0.12811363 0.45038594]
 [0.37079802 0.92676499 0.64386512 0.82276161 0.4434142 ]
 [0.22723872 0.55458479 0.06381726 0.82763117 0.6316644 ]
 [0.75808774 0.35452597 0.97069802 0.89312112 0.7783835 ]]


# Random Numbers from Choice

In [17]:
array = gen(pcg(seed=42))
print(array.choice([1,2,3,4,5],size=(5,5)))

[[1 4 4 3 3]
 [5 1 4 2 1]
 [3 5 4 4 4]
 [4 3 1 5 3]
 [3 2 1 5 4]]


# Poisson Distribution

Over a Fixed Interval Time, Distance or Space

We Expect an Event to Occur Exactly Once.

In [18]:
array = gen(pcg(seed=42))
print(array.poisson(size=(5,5)))

[[1 2 3 1 3]
 [0 1 3 3 1]
 [0 3 1 0 0]
 [1 1 2 2 0]
 [1 0 0 3 1]]


In [19]:
array = gen(pcg(seed=42))
print(array.poisson(lam=10 ,size=(5,5)))

[[13  6  9 11  9]
 [10 13 13 13 10]
 [ 6  8 10  6  7]
 [ 9 12  9 12  7]
 [13 10  6 12 11]]


# Binomial Distribution

Measures how many times a certain outcome can Appear over a Series of Trials

There are only 2 Possible Outcomes

In [20]:
array = gen(pcg(seed=42))
print(array.binomial(n=100, p=0.4 ,size=(5,5)))
# n : Number of Trials | p : Probability of getting Desired Outcome

[[46 31 34 39 40]
 [34 38 31 45 46]
 [35 38 43 35 39]
 [39 43 32 45 43]
 [44 42 38 37 41]]


# Logistic Distribution

In [21]:
array = gen(pcg(seed=42))
print(array.logistic(loc=9, scale=1.2 ,size=(5,5)))

[[10.47694276  8.70514189 11.16443192 10.00175501  6.28360337]
 [13.4272907  10.39072568 10.56163575  6.69871023  8.76106623]
 [ 8.36544623 12.0456317   9.71061567 10.84220503  8.72721958]
 [ 7.53123711  9.26305535  5.77705551 10.8827173   9.64723651]
 [10.37066884  8.28095594 13.20043258 11.54763119 10.50752509]]


# Application

When Real Data isn't Available

Sometimes we need Pseudo Random Data to Test How well a Program Performs.
 