# NumPy

Element Wise Properties

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])
print(f'Array a : {a}')
print(f'Array b : \n{b}')

Array a : [1 2 3]
Array b : 
[[1 2 3]
 [4 5 6]]


Mathematical Computation takes place with Each Element within an Array

In [3]:
print(a + 2) # Adding 2 to 1D Array

[3 4 5]


In [4]:
print(b + 2) # Adding 2 to 2D Array

[[3 4 5]
 [6 7 8]]


In [5]:
print(a + b)  # Broadcasting

[[2 4 6]
 [5 7 9]]


In [6]:
print(a + b[0]) # Element Wise Addition takes place.

[2 4 6]


In [7]:
a = np.array([1,2,3], dtype="float")
print(a)

[1. 2. 3.]


# Float

In [8]:
float_array = np.array([[1,2,3],[4,5,6]], dtype=np.float)
print(float_array)

[[1. 2. 3.]
 [4. 5. 6.]]


# Complex

In [9]:
complex_array = np.array([[1,2,3],[4,5,6]], dtype=np.complex)
print(complex_array)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


# Boolean

In [10]:
bool_array = np.array([[1,0,1],[-1,1,0]], dtype=np.bool)
print(bool_array)

[[ True False  True]
 [ True  True False]]


# String

In [11]:
str_array = np.array([[1,2,3],[4,5,6]], dtype=np.str)
print(str_array)
print(f'\n{str_array.dtype} : Unicode Value of Length upto 1')

[['1' '2' '3']
 ['4' '5' '6']]

<U1 : Unicode Value of Length upto 1


# Squareroot

In [12]:
print(np.sqrt(float_array)) # Elementwise Squareroot

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


# Characteristics of NumPy Functions

[NumPy Universal Functions](https://numpy.org/doc/stable/reference/ufuncs.html)

## Broadcasting

In [13]:
vector_1D = np.array([1,2,3])
vector_2D = np.array([[1],[2]])
matrix = np.array([[1,2,3],[4,5,6]])
print(f'1 Dimensional Vector : \n{vector_1D}\n')
print(f'2 Dimensional Vector : \n{vector_2D}\n')
print(f'Matrix : \n{matrix}')

1 Dimensional Vector : 
[1 2 3]

2 Dimensional Vector : 
[[1]
 [2]]

Matrix : 
[[1 2 3]
 [4 5 6]]


In [14]:
print(vector_1D + matrix)

[[2 4 6]
 [5 7 9]]


In [15]:
print(np.add(vector_1D, matrix))

[[2 4 6]
 [5 7 9]]


In [16]:
print(np.add(vector_2D, matrix))

[[2 3 4]
 [6 7 8]]


# Type Casting

In [17]:
print(np.add(matrix, vector_1D, dtype = np.float))

[[2. 4. 6.]
 [5. 7. 9.]]


# Axis

Applying a Function along An Axis

axis = 0 | Each Column of the Array

axis = 1 | Each Row of the Array

In [18]:
print(f'{matrix}\n')
print(f'Axis 0 | Each Column \n{np.sum(matrix, axis = 0)}\n')
print(f'Axis 1 | Each Row \n{np.sum(matrix, axis = 1)}')

[[1 2 3]
 [4 5 6]]

Axis 0 | Each Column 
[5 7 9]

Axis 1 | Each Row 
[ 6 15]


# ndarray

In [19]:
# 0 Dimensional Array
a = np.array(1)

print(f'0 Dimension Array {a}\n')
print(f'Shape of 0 Dimension Array {a.shape}') # Single Point in N Dimensional Space.

0 Dimension Array 1

Shape of 0 Dimension Array ()


In [20]:
# 1D Array
a = np.array([1,2,3])

print(f'1D Array {a}\n')
print(f'Shape of 1D Array {a.shape}') # Number of Elements in An 1D Array.

# Number of Points Located on a Line (Geometric Space)

1D Array [1 2 3]

Shape of 1D Array (3,)


In [21]:
# 2D Array

a = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(f'2D Array {a}\n')
print(f'Shape of 2D Array {a.shape}') # 3 Rows and 3 Columns

2D Array [[1 2 3]
 [4 5 6]
 [7 8 9]]

Shape of 2D Array (3, 3)


# Slicing

In [22]:
a = np.array([[1,2,3,1],[4,5,6,0],[7,8,9,1],[0,1,0,1]])
print(a)

[[1 2 3 1]
 [4 5 6 0]
 [7 8 9 1]
 [0 1 0 1]]


In [23]:
print(a[-1::-1,::-1])

[[1 0 1 0]
 [1 9 8 7]
 [0 6 5 4]
 [1 3 2 1]]


In [24]:
print(a[0:1,0:1].squeeze()) # To get the Value in Int

1


In [25]:
print(np.squeeze(a[0:1,0:1]))

1


In [26]:
print(type(a[0:1,0:1].squeeze()))

<class 'numpy.ndarray'>


In [27]:
print(np.squeeze(a[0:1,0:1]).shape)

()
